argo-cd:
    configs:
        params:
            server.insecure: true
    server:
        ingress:
            enabled: true
            ingressClassName: nginx
            hostname: argocd.vsamdele.space
            tls: true