gitea:
  gitea:
    admin:
      username: gerasim9393
      password: Cjukfcbt19
      email: gerasim9393@mail.ru
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: gitea.vsamdele.space
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls
        hosts:
          - gitea.vsamdele.space