grafana:
  adminUser: admin
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus.vsamdele.space
          access: proxy
          isDefault: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.vsamdele.space
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.vsamdele.space